### ISSUE TITLE
Cryptic Analysisへの表示項目の追加(価格差)について

### ISSUE THREAD

**Issue by ghost** [bitrinjani/cryptic-analysis#1]
お世話になっております。

現状、Cryptic Analysisの価格差に関する表示はSpreadのみとなっておりますが、R2に実装されているパーセンテージでの価格差(%)の表示もあると視認性がより改善されると考えております。

ご検討のほどよろしくお願いいたします。

**Comment by bitrinjani** [comment]
提案ありがとうございます。検討します。

**Comment by bitrinjani** [comment]
以下のように追加しました。ブラウザキャッシュをクリアしないと反映されない模様です。

### ¥1,371
Expected Profit
Spread : -¥27,423
Volume: 0.05 BTC
**Profit Ratio: 1.68%**
